amitlamdim/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("website.urls")),

]

website/urls.py
from django.urls import path


from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("", views.index, name="index"),
    path("profile/", views.myprofile, name="myprofile"),
    path("frealancers/", views.get_frealancers, name="frealancers"),
    path("login/", views.login_page, name="login_page"),
    path("search/", views.search, name="search"),
    path("register/", views.register_page, name="register_page"),
    path("logout/", views.logout_page, name="logout_page"),
    path("inbox/", views.inbox, name="inbox"),
    path("vaild/", views.vaild_account, name="vaild_account"),
    path("vaild/<user_id>", views.vaild_account, name="vaild_account"),
    path("vaild/<user_id>/<token>", views.vaild_account, name="vaild_account"),
    path("rest_password/", auth_views.PasswordResetView.as_view(template_name = 'reset/password_reset.html', html_email_template_name='reset/password_reset_email.html'), name='reset_password'),
    path("rest_password_sent/", auth_views.PasswordChangeDoneView.as_view(), name='password_reset_done'),
    path("rest/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(template_name = 'reset/password_confirm.html'), name='password_reset_confirm'),
    path("rest_password_complete/", auth_views.PasswordResetCompleteView.as_view(template_name = 'reset/password_reset_done.html'), name='password_reset_complete'),
    ]

website/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
import datetime
from firebase_admin import credentials, initialize_app, storage
from django.conf import settings
import random
# Category, Expertise, Userdata, UserExpertise, Messages, User, Resume

class Category(models.Model):
    category_name = models.CharField(null=True, max_length=100)
    design = models.CharField(null=False, max_length=100, default='success')

    def __str__(self):
        return self.category_name


class Expertise(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    text = models.CharField(null=True, max_length=100)

    def __str__(self):
        return self.text



class Userdata(models.Model):
    uid = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    first_name = models.CharField(null=True, max_length=100, default=None)
    last_name = models.CharField(null=True, max_length=100, default=None)
    github_link = models.CharField(null=True, max_length=300, default=None)
    linkedin_link = models.CharField(null=True, max_length=300, default=None)
    website = models.CharField(null=True, max_length=300, default=None)
    profile_pic = models.CharField(null=True, max_length=350, default=None)
    background = models.CharField(null=True, max_length=300, default=None)
    experience_years = models.IntegerField(default=timezone.now().year)
    show = models.BooleanField(default=True)
    update = models.DateTimeField(default=timezone.now)
    salary_per_hour = models.IntegerField(default=0)
    details = models.CharField(null=True, max_length=1500, default=None)
    phone = models.CharField(null=True, max_length=20, default=None)
    city = models.CharField(null=True, max_length=20, default=None)

    def is_valid(self):
        return self.first_name and self.last_name and self.userexpertise_set

    def get_new_mes(self):
        return len(self.messages_set.filter(mes_read=False).all())

    def get_all_mes(self):
        return self.messages_set.order_by('-id')
    
    def get_exp(self):
        all_exp = []
        for kkk in Expertise.objects.values('category_id').distinct().all():
            query = Category.objects.filter(pk = kkk['category_id'])
            if query: all_exp.append({'category':query[0].category_name, 'design':query[0].design, 'id':query[0].id})
        return all_exp
    
    def get_exp_details(self):
        result = self.get_exp()
        for each in result:
            each['expertise'] = UserExpertise.objects.filter(my_expertise__category__id = each['id'])
        return result

    def toJSON(self):
        years = timezone.now().year - self.experience_years
        return {"id": self.uid.id,
                "first_name": self.first_name,
                "last_name": self.last_name,
                "github_link": self.github_link,
                "background": self.background,
                "website": self.website,
                "profile_pic": self.profile_pic,
                "experience": f'{years} - {years + 1}',
                "show": self.show,
                "update": self.update,
                "salary_per_hour": f'{self.salary_per_hour} ₪',
                "experience_titels": self.get_exp()}
    
    def __str__(self):
        return self.uid.username


class UserExpertise(models.Model):
    userdata = models.ForeignKey(Userdata, on_delete=models.CASCADE)
    my_expertise = models.ForeignKey(Expertise, on_delete=models.CASCADE)
    description = models.CharField(null=True, max_length=500)


    def __str__(self):
        return self.my_expertise.text


class Messages(models.Model):
    user_to = models.ForeignKey(Userdata, on_delete=models.CASCADE)
    pub_date = models.DateTimeField(default=timezone.now)
    mes_content = models.CharField(null=False, max_length=500)
    mes_from = models.CharField(null=False, max_length=100)
    mes_contact = models.CharField(null=False, max_length=100)
    mes_read = models.BooleanField(default=False)

    def read_set(self):
        if self.mes_read:
            return False
        else:
            self.mes_read = True
            self.save()
            return True

    def get_date_format(self):
        return self.pub_date.strftime('%d/%m/%Y %H:%M')

    def __str__(self):
        return self.mes_from

class Resume(models.Model):
    user = models.ForeignKey(Userdata, on_delete=models.CASCADE)
    title = models.CharField(null=False, max_length=100)
    text = models.CharField(null=False, max_length=500)
    start_year = models.IntegerField(null=True)
    end_year = models.IntegerField(null=True)

    def get_years(self):
        if self.start_year == self.end_year:
            return self.start_year
        return f'{self.end_year} - {self.start_year}'

class Portfolio(models.Model):
    userdata = models.ForeignKey(Userdata, on_delete=models.CASCADE)
    pic = models.CharField(null=True, max_length=300, default=None)
    title = models.CharField(null=True, max_length=30, default=None)
    link = models.CharField(null=True, max_length=300, default=None)

website/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from datetime import datetime
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.core.mail import EmailMessage, get_connection
from django.conf import settings
from django import forms
from captcha.fields import ReCaptchaField
from captcha.widgets import ReCaptchaV2Checkbox
from django.utils import timezone
import random
from django.http import HttpResponse
from website.models import Userdata, Messages


class Recaptcha(forms.Form):
    captcha = ReCaptchaField(widget=ReCaptchaV2Checkbox, label="")


def index(request):
    return render(request, 'base.html', {'title_page': 'first'})


def inbox(request):
    return render(request, 'messages.html', {'title_page': 'ההודעות שלי'})


def get_frealancers(request):
    return render(request, 'freelancers.html')


def send_email(toemail, mysubject, mymessage):
    with get_connection(
        host=settings.EMAIL_HOST,
        port=settings.EMAIL_PORT,
        username=settings.EMAIL_HOST_USER,
        password=settings.EMAIL_HOST_PASSWORD,
        use_tls=settings.EMAIL_USE_TLS
    ) as connection:
        subject = mysubject
        email_from = settings.EMAIL_HOST_USER
        recipient_list = [toemail, ]
        message = mymessage
        EmailMessage(subject, message, email_from,
                     recipient_list, connection=connection).send()


def send_vaildation_email(email, name, user_id, token):
    mes = f'שלום {name}, \n תודה שנרשמת לאתר! רצינו לוודא שזה באמת המייל שלך מאחר ותוכל להגדיר שאתה מעוניין לקבל הודעות ממשתמשים שיתעניינו בדירות שתפרסם באתר.\n על מנת להשלים את תהליך ההרשמה יש ללחוץ על הקישור המופיע במייל זה. לאחר לחיצה עליו, חשבונך יופעל.\n הקישור: \n{settings.MY_URL}vaild/{user_id}/{token} \n תודה!'
    send_email(email, 'אימות כתובת המייל', mes)


def login_page(request):
    user = request.user
    if user.is_authenticated:
        if user.last_name != '1':
            if request.method == 'GET':
                return render(request, 'login.html', {'title_page': 'Log-in'})
        else:
            return redirect('index')

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user:
            if user.is_authenticated:
                logout(request)
            login(request, user)
            if user.last_name != '1':
                return render(request, 'login.html', {'log': 'נא לאמת את כתובת המייל באמצעות מייל לאימות סיסמא שנשלח אליך בעת ההרשמה', 'title_page': 'Log-in'})
            else:
                return redirect('index')
        else:
            messages.error(request, f"log")
        return render(request, 'login.html', {'username1': username, 'log': 'כנראה הזנת שם משתמש או סיסמא לא נכונים', 'title_page': 'Log-in'})

    next = request.GET.get('next')
    if next:
        mes = ''
        if next == '/rest_password_sent/':
            mes = 'אם המייל שהזנת רשום, נשלח אליך קישור לאיפוס הסיסמא, נא לבדוק בתיבת המייל או בתיבת הודעות הספאם'
        elif next == 'set':
            mes = 'סיסמתך שונתה בהצלחה, ניתן להתחבר'
        return render(request, 'login.html', {'reset': mes, 'title_page': 'Log-in'})
    return render(request, 'login.html', {'title_page': 'Log-in'})


def logout_page(request):
    logout(request)
    return redirect('index')


def vaild_account(request, user_id=0, token=None):
    mes = None
    if request.user:
        if request.user.is_authenticated and request.user.last_name == '1':
            return redirect('index')

    if user_id and token:
        user = User.objects.filter(pk=user_id).all()
        if user:
            user = user[0]
            if user.last_name == token:
                user.last_name = '1'
                user.save()
                mes = 'אימות כתובת המייל הושלמה, ניתן להתחבר כעת'
                if request.user.is_authenticated:
                    return redirect('index')
            elif user.last_name == '1':
                mes = 'נראה שכבר אישרת את כתובת המייל, ניתן להתחבר'
            if mes:
                return render(request, 'login.html', {'reset': mes, 'title_page': 'Log-in'})
    return render(request, 'login.html', {'log': 'שגיאה באימות החשבון', 'title_page': 'Log-in'})

# custom 404 view


def custom_404(request, exception):
    return render(request, '404.html', status=404)


def register_page(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        repassword = request.POST.get('repassword')
        firstname = request.POST.get('firstname')
        email = request.POST.get('email')
        msg = []
        if username:
            if len(username) < 4:
                msg.append('שם המשתמש צריך להכיל לפחות 4 תווים')
        if User.objects.filter(email=email).all():
            msg.append('מייל זה נמצא בשימוש')
        if User.objects.filter(username=username).all():
            msg.append('שם משתמש זה נמצא בשימוש')
        elif repassword == password and password and username and email and firstname and not msg:
            try:
                options = 'Aa5B1b2C3r4Df5q6E4o7u28F9Q1mRS'
                vaildation = [options[random.randint(
                    0, len(options)-1)] for k in range(16)]
                user = User.objects.create_user(
                    username=username, email=email, first_name=firstname, last_name=''.join(vaildation), password=password)
                user.save()
            except Exception as e:
                msg.append(e)
            user1 = authenticate(request, username=username, password=password)
            if user1:
                login(request, user1)
                send_vaildation_email(
                    user1.email, user1.first_name, user.id, user1.last_name)
                return render(request, 'login.html', {'reset': 'שלחנו לך מייל לאימות כתובת המייל שהזנת, מאחר שתוכל לבחור לקבל מיילים ממתעניינים בדירה נבקש לאשר שזאת כתובת המייל שלך. תודה', 'title_page': 'Log-in'})
        elif repassword != password:
            msg.append('הסיסמאות לא תואמות')
        if not username or not password or not firstname or not firstname or not email:
            msg.append('נא למלא את כל השדות')

        return render(request, 'login.html', {'username2': username, 'email': email, 'firstname': firstname, 'reg': 'reg', 'msg': msg, 'title_page': 'Log-in'})
    return render(request, 'login.html', {'reg': 'reg', 'msg': [], 'title_page': 'Log-in'})


def search(request):
    expertise_to_search = [2]
    query = Userdata.objects.filter(
        userexpertise__id__in=expertise_to_search).distinct()
    return JsonResponse([k.toJSON() for k in query.all()], safe=False)

def myprofile(request):
    return render(request, 'myprofile.html', {'title_page': 'הפרופיל שלי'})

website/templates/403_csrf.html
<meta http-equiv="Refresh" content="0; url='{% url 'login_page'%}" />

website/templates/myprofile.html
{% extends "base.html" %}
{% block content %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>

    .panel {
  box-shadow: none;
}
.panel-heading {
  border-bottom: 0;
}
.panel-title {
    margin-bottom: -15px;
  font-size: 17px;
}
.panel-title > small {
  font-size: .75em;
  color: #999999;
}
.panel-body *:first-child {
  margin-top: 0;
}
.panel-footer {
  border-top: 0;
}

.panel-default > .panel-heading {
    color: #333333;
    background-color: transparent;
    border-color: rgba(0, 0, 0, 0.07);
}

/**
 * Profile
 */
/*** Profile: Header  ***/
.profile__avatar {
  float: right;
  width: 60px;
  height: 60px;
  border-radius: 50%;
  margin-right: 20px;
  overflow: hidden;
}
@media (min-width: 768px) {
  .profile__avatar {
    width: 100px;
    height: 100px;
  }
}
.profile__avatar > img {
  width: 100%;
  height: auto;
}
.profile__header {
  overflow: hidden;
}
.profile__header p {
  margin: 20px 20px;
}
.profile__header h4 {
  margin: 20px 20px;
}
/*** Profile: Table ***/
/*** Profile: Recent activity ***/
.profile-comments__item {
  position: relative;
  padding: 15px 16px;
  border-bottom: 1px solid rgba(0, 0, 0, 0.05);
}
.profile-comments__item:last-child {
  border-bottom: 0;
}
.profile-comments__item:hover,
.profile-comments__item:focus {
  background-color: #f5f5f5;
}
.profile-comments__item:hover .profile-comments__controls,
.profile-comments__item:focus .profile-comments__controls {
  visibility: visible;
}
.profile-comments__controls {
  position: absolute;
  top: 0;
  right: 0;
  padding: 5px;
  visibility: hidden;
}
.profile-comments__controls > a {
  display: inline-block;
  padding: 2px;
  color: #999999;
}
.profile-comments__controls > a:hover,
.profile-comments__controls > a:focus {
  color: #333333;
}
.profile-comments__avatar {
  display: block;
  float: left;
  margin-right: 20px;
  width: 40px;
  height: 40px;
  border-radius: 50%;
  overflow: hidden;
}
.profile-comments__avatar > img {
  width: 100%;
  height: auto;
}
.profile-comments__body {
  overflow: hidden;
}
.profile-comments__sender {
  color: #333333;
  font-weight: 500;
  margin: 5px 0;
}
.profile-comments__sender > small {
  margin-left: 5px;
  font-size: 12px;
  font-weight: 400;
  color: #999999;
}
@media (max-width: 767px) {
  .profile-comments__sender > small {
    display: block;
    margin: 5px 0 10px;
  }

}
.profile-comments__content {
  color: #999999;
}
/*** Profile: Contact ***/
.profile__contact-btn {
  padding: 12px 20px;
  margin-bottom: 20px;
}
.profile__contact-hr {
  position: relative;
  border-color: rgba(0, 0, 0, 0.1);
  margin: 40px 0;
}
.profile__contact-hr:before {
  content: "OR";
  display: block;
  padding: 10px;
  position: absolute;
  top: 50%;
  left: 50%;
  -webkit-transform: translate(-50%, -50%);
  transform: translate(-50%, -50%);
  background-color: #f5f5f5;
  color: #c6c6cc;
}
.profile__contact-info-item {
  margin-bottom: 30px;
}
.profile__contact-info-item:before,
.profile__contact-info-item:after {
  content: " ";
  display: table;
}
.profile__contact-info-item:after {
  clear: both;
}
.profile__contact-info-item:before,
.profile__contact-info-item:after {
  content: " ";
  display: table;
}
.profile__contact-info-item:after {
  clear: both;
}
.profile__contact-info-icon {
  margin: 10px;
  float: right;
  font-size: 18px;
  color: #999999;
}
.profile__contact-info-body {
  overflow: hidden;
  padding-left: 20px;
  color: #999999;
}
.profile__contact-info-body a {
  color: #999999;
}
.profile__contact-info-body a:hover,
.profile__contact-info-body a:focus {
  color: #999999;
  text-decoration: none;
}
.profile__contact-info-heading {
  margin-top: 2px;
  margin-bottom: 5px;
  font-weight: 500;
  color: #999999;
}
.btn-social{position:relative;padding-left:44px;text-align:left;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.btn-social :first-child{position:absolute;left:0;top:0;bottom:0;width:32px;line-height:34px;font-size:1.6em;text-align:center;border-right:1px solid rgba(0,0,0,0.2)}
.btn-social.btn-lg{padding-left:61px}.btn-social.btn-lg :first-child{line-height:45px;width:45px;font-size:1.8em}
.btn-social.btn-sm{padding-left:38px}.btn-social.btn-sm :first-child{line-height:28px;width:28px;font-size:1.4em}
.btn-social.btn-xs{padding-left:30px}.btn-social.btn-xs :first-child{line-height:20px;width:20px;font-size:1.2em}
.btn-social-icon{position:relative;padding-left:44px;text-align:left;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;height:34px;width:34px;padding:0}.btn-social-icon :first-child{position:absolute;left:0;top:0;bottom:0;width:32px;line-height:34px;font-size:1.6em;text-align:center;border-right:1px solid rgba(0,0,0,0.2)}
.btn-social-icon.btn-lg{padding-left:61px}.btn-social-icon.btn-lg :first-child{line-height:45px;width:45px;font-size:1.8em}
.btn-social-icon.btn-sm{padding-left:38px}.btn-social-icon.btn-sm :first-child{line-height:28px;width:28px;font-size:1.4em}
.btn-social-icon.btn-xs{padding-left:30px}.btn-social-icon.btn-xs :first-child{line-height:20px;width:20px;font-size:1.2em}
.btn-social-icon :first-child{border:none;text-align:center;width:100% !important}
.btn-social-icon.btn-lg{height:45px;width:45px;padding-left:0;padding-right:0}
.btn-social-icon.btn-sm{height:30px;width:30px;padding-left:0;padding-right:0}
.btn-social-icon.btn-xs{height:22px;width:22px;padding-left:0;padding-right:0}
.btn-github{color:#fff;background-color:#444;border-color:rgba(0,0,0,0.2)}.btn-github:hover,.btn-github:focus,.btn-github:active,.btn-github.active,.open .dropdown-toggle.btn-github{color:#fff;background-color:#303030;border-color:rgba(0,0,0,0.2)}
.btn-github:active,.btn-github.active,.open .dropdown-toggle.btn-github{background-image:none}
.btn-github.disabled,.btn-github[disabled],fieldset[disabled] .btn-github,.btn-github.disabled:hover,.btn-github[disabled]:hover,fieldset[disabled] .btn-github:hover,.btn-github.disabled:focus,.btn-github[disabled]:focus,fieldset[disabled] .btn-github:focus,.btn-github.disabled:active,.btn-github[disabled]:active,fieldset[disabled] .btn-github:active,.btn-github.disabled.active,.btn-github[disabled].active,fieldset[disabled] .btn-github.active{background-color:#444;border-color:rgba(0,0,0,0.2)}
.btn-linkedin{color:#fff;background-color:#007bb6;border-color:rgba(0,0,0,0.2)}.btn-linkedin:hover,.btn-linkedin:focus,.btn-linkedin:active,.btn-linkedin.active,.open .dropdown-toggle.btn-linkedin{color:#fff;background-color:#005f8d;border-color:rgba(0,0,0,0.2)}
.btn-linkedin:active,.btn-linkedin.active,.open .dropdown-toggle.btn-linkedin{background-image:none}
.btn-linkedin.disabled,.btn-linkedin[disabled],fieldset[disabled] .btn-linkedin,.btn-linkedin.disabled:hover,.btn-linkedin[disabled]:hover,fieldset[disabled] .btn-linkedin:hover,.btn-linkedin.disabled:focus,.btn-linkedin[disabled]:focus,fieldset[disabled] .btn-linkedin:focus,.btn-linkedin.disabled:active,.btn-linkedin[disabled]:active,fieldset[disabled] .btn-linkedin:active,.btn-linkedin.disabled.active,.btn-linkedin[disabled].active,fieldset[disabled] .btn-linkedin.active{background-color:#007bb6;border-color:rgba(0,0,0,0.2)}
.image-fill{
  width: 100%;
  display: block;
  margin: 0 auto;
  position: relative;
}
.image-fill img{
  display: block;
  width: 100%;
  height: 300px;
  object-fit: cover;
	object-position: 25% 25%; 
}
.conti{
  width: 75%; 
  margin: 0 auto;
}
@media (max-width: 767px) {
  .conti{
    width: 100%;
  }

}
</style>

<div dir="rtl" class="row container">
    <div class="col-xs-12 col-sm-9">
      
      <!-- User profile -->
      <div class="panel panel-default">
        <div class="panel-heading">
        </div>
        <div class="panel-body">
          <div class="profile__avatar">
            <img src="{% if user.userdata.profile_pic %}{{user.userdata.profile_pic}}{% else %}https://cdn.vectorstock.com/i/preview-1x/62/59/default-avatar-photo-placeholder-profile-icon-vector-21666259.jpg{% endif %}" alt="...">
          </div>
          <div class="profile__header">
            <h4>{{user.userdata.first_name}} {{user.userdata.last_name}}</h4>
            <p class="text-muted">
                {{user.userdata.details}}
            </p>
            <p>
              {% if user.userdata.website %} <a target="_blank" href="{{user.userdata.website}}">{{user.userdata.website}}</a> {% endif %}
            </p>
            
          </div>
        </div>
      </div>

      <!-- User info -->
      {%for tbn in user.userdata.get_exp_details%}
      <div class="panel panel-default">
        <div class="panel-heading">
        <h4 class="panel-title"><span class="label label-{{tbn.design}}">{{tbn.category}}</span></h4>
        </div>
        <div class="panel-body row">
          <table dir="rtl" class="table">
            <tbody>
            {% for ttr in tbn.expertise%}
            <tr>
                <th class="col-md-1 col-xs-2" dir="rtl"><strong>{{ttr}}</strong></th>
                <td class="col-md-11 col-xs-10">{{ttr.description}}</td>
              </tr>
            {% endfor%}
            </tbody>
          </table>
        </div>
      </div>
      {% endfor %}

    <div class="panel panel-default">
        <div class="panel-heading">
        <h4 class="panel-title">קורות חיים</h4>
        </div>
        <div class="panel-body row">
          <table dir="rtl" class="table">
            <tbody>
            {% for myres in user.userdata.resume_set.all %}
            <tr>
                <th class="col-md-2 col-xs-3" dir="rtl"><strong>{{myres.title}}</strong></th>
                <th class="col-md-2 col-xs-3" dir="rtl"><strong>{{myres.get_years}}</strong></th>
                <td class="col-md-8 col-xs-6">{{myres.text}}</td>
              </tr>
            {% endfor%}
            </tbody>
          </table>
        </div>
      </div>
      {% if user.userdata.portfolio_set.all %}
      <div class="panel panel-default">
        <div class="panel-heading">
        <h4 class="panel-title">תיק עבודות</h4>
        </div>
        <div class="panel-body">
          <div class="conti">
            <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">          
              <!-- Wrapper for slides -->
              {% for prof in user.userdata.portfolio_set.all %}
              <div id="mycaro" class="carousel-inner" role="listbox">
                <div class="item">
                  <div class="image-fill">
                    <img src="{{prof.pic}}" alt="...">
                  </div>
                  <div class="carousel-caption">
                    <th>{% if prof.link %} <a class="btn btn-link" target="_blank" href="{{prof.link}}">{{prof.title}}</a>{% else %}{{prof.title}}{% endif %}</th>
                  </div>
                </div>
                {% endfor %}
                
              </div>
            
              <!-- Controls -->
              <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
              </a>
              <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
              </a>
            </div>
          </div>
        </div>
      </div>
      {% endif %}
      
     

    </div>
    <div class="col-xs-12 col-sm-3">
      
      <!-- Contact user -->
      <p>
        <a href="#" class="profile__contact-btn btn btn-lg btn-block btn-info" data-toggle="modal" data-target="#profile__contact-form">
          צור קשר
        </a>
        <div class="text-center">
                  <!-- just add href= for your links, like this: -->
                  {% if user.userdata.github_link %}<a target="_blank" href="{{user.userdata.github_link}}" class="btn btn-social-icon btn-github"><i class="fa fa-github"></i></a>{% endif %}
                  {% if user.userdata.linkedin_link %}<a target="_blank" href="{{user.userdata.linkedin_link}}" class="btn btn-social-icon btn-linkedin"><i class="fa fa-linkedin"></i></a>{% endif %}
                </div>
      </p>

      <hr class="profile__contact-hr">
      
      <!-- Contact info -->
      <div  class="profile__contact-info">
        <div class="profile__contact-info-item">
          <div class="profile__contact-info-icon">
            <i class="fa fa-ils"></i>
          </div>
          <div class="profile__contact-info-body">
            <h5 class="profile__contact-info-heading"><strong>מחיר לשעת עבודה</strong></h5>
            {{user.userdata.salary_per_hour}} ₪
          </div>
        </div>
        {% if user.userdata.city %}
      <div  class="profile__contact-info">
        <div class="profile__contact-info-item">
          <div class="profile__contact-info-icon">
            <i class="fa fa-map-marker"></i>
          </div>
          <div class="profile__contact-info-body">
            <h5 class="profile__contact-info-heading"><strong>עיר</strong></h5>
            {{user.userdata.city}}
          </div>
        </div>
        {% endif %}
        {% if user.userdata.phone %}
        <div class="profile__contact-info-item">
          <div class="profile__contact-info-icon">
            <i class="fa fa-phone"></i>
          </div>
          <div class="profile__contact-info-body">
            <h5 class="profile__contact-info-heading"><strong>מספר טלפון</strong></h5>
            {{user.userdata.phone}}
          </div>
        </div>
        {% endif %}
      </div>

    </div>
  </div>

<script>
  mycaro.firstElementChild.classList.add('active');
</script>
{% endblock %}